# Generated by Django 4.0 on 2021-12-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='dob',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
