# Generated by Django 4.0 on 2021-12-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('feedback', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
